apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vmaas

resources:
  - cloudkit.openshift.io_cloudkitvms.yaml
  - udn.yaml
  - nfs-subdir-provisioner.yaml
  - nfs-rbac.yaml

labels:
- pairs:
    cloudkit.openshift.io/project: cloudkit-vmaas
