apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: innabox

metadata:
  name: cloudkit-base

resources:
  - shared
  - cloudkit-aap
  - cloudkit-operator
  - fulfillment-service

# Common labels for all CloudKit components
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cloudkit

images:
  - name: fulfillment-service
    newName: ghcr.io/innabox/fulfillment-service
    newTag: latest
  - name: cloudkit-aap-ee
    newName: ghcr.io/innabox/cloudkit-aap-ee
    newTag: latest
  - name: cloudkit-operator
    newName: ghcr.io/innabox/cloudkit-operator
    newTag: latest
